// COMPILER GENERATED CODE
// THIS WILL BE OVERWRITTEN AT EACH GENERATION
// EDIT AT YOUR OWN RISK

using System.Runtime.CompilerServices;

namespace ShadowSys118.Model.SS118Data
{
    [CompilerGenerated]
    public partial class Outputs
    {
        public short StateTxTapV { get; set; }
        public short StateSn1CapBkrV { get; set; }
        public short StateSn2CapBkrV { get; set; }
        public short StateSn1BusBkrV { get; set; }
        public short StateSn2BusBkrV { get; set; }
        public double MeasTxVoltV { get; set; }
        public double MeasSn1VoltV { get; set; }
        public double MeasSn2VoltV { get; set; }
        public double MeasTxMwV { get; set; }
        public double MeasTxMvrV { get; set; }
        public double MeasGn1MwV { get; set; }
        public double MeasGn1MvrV { get; set; }
        public double MeasGn2MwV { get; set; }
        public double MeasGn2MvrV { get; set; }
        public short StateSnB34CapBkrV { get; set; }
        public short StateSnB44CapBkrV { get; set; }
        public short StateSnB45CapBkrV { get; set; }
        public short StateSnB48CapBkrV { get; set; }
        public short StateSnB74CapBkrV { get; set; }
        public short StateSnB105CapBkrV { get; set; }
        public double MeasB1VoltV { get; set; }
        public double MeasB2VoltV { get; set; }
        public double MeasB3VoltV { get; set; }
        public double MeasB4VoltV { get; set; }
        public double MeasB5VoltV { get; set; }
        public double MeasB6VoltV { get; set; }
        public double MeasB7VoltV { get; set; }
        public double MeasB8VoltV { get; set; }
        public double MeasB9VoltV { get; set; }
        public double MeasB10VoltV { get; set; }
        public double MeasB11VoltV { get; set; }
        public double MeasB12VoltV { get; set; }
        public double MeasB13VoltV { get; set; }
        public double MeasB14VoltV { get; set; }
        public double MeasB15VoltV { get; set; }
        public double MeasB16VoltV { get; set; }
        public double MeasB17VoltV { get; set; }
        public double MeasB18VoltV { get; set; }
        public double MeasB19VoltV { get; set; }
        public double MeasB20VoltV { get; set; }
        public double MeasB21VoltV { get; set; }
        public double MeasB22VoltV { get; set; }
        public double MeasB23VoltV { get; set; }
        public double MeasB24VoltV { get; set; }
        public double MeasB25VoltV { get; set; }
        public double MeasB26VoltV { get; set; }
        public double MeasB27VoltV { get; set; }
        public double MeasB28VoltV { get; set; }
        public double MeasB29VoltV { get; set; }
        public double MeasB30VoltV { get; set; }
        public double MeasB31VoltV { get; set; }
        public double MeasB32VoltV { get; set; }
        public double MeasB33VoltV { get; set; }
        public double MeasB34VoltV { get; set; }
        public double MeasB35VoltV { get; set; }
        public double MeasB36VoltV { get; set; }
        public double MeasB37VoltV { get; set; }
        public double MeasB38VoltV { get; set; }
        public double MeasB39VoltV { get; set; }
        public double MeasB40VoltV { get; set; }
        public double MeasB41VoltV { get; set; }
        public double MeasB42VoltV { get; set; }
        public double MeasB43VoltV { get; set; }
        public double MeasB44VoltV { get; set; }
        public double MeasB45VoltV { get; set; }
        public double MeasB46VoltV { get; set; }
        public double MeasB47VoltV { get; set; }
        public double MeasB48VoltV { get; set; }
        public double MeasB49VoltV { get; set; }
        public double MeasB50VoltV { get; set; }
        public double MeasB51VoltV { get; set; }
        public double MeasB52VoltV { get; set; }
        public double MeasB53VoltV { get; set; }
        public double MeasB54VoltV { get; set; }
        public double MeasB55VoltV { get; set; }
        public double MeasB56VoltV { get; set; }
        public double MeasB57VoltV { get; set; }
        public double MeasB58VoltV { get; set; }
        public double MeasB59VoltV { get; set; }
        public double MeasB60VoltV { get; set; }
        public double MeasB61VoltV { get; set; }
        public double MeasB62VoltV { get; set; }
        public double MeasB63VoltV { get; set; }
        public double MeasB64VoltV { get; set; }
        public double MeasB65VoltV { get; set; }
        public double MeasB66VoltV { get; set; }
        public double MeasB67VoltV { get; set; }
        public double MeasB68VoltV { get; set; }
        public double MeasB69VoltV { get; set; }
        public double MeasB70VoltV { get; set; }
        public double MeasB71VoltV { get; set; }
        public double MeasB72VoltV { get; set; }
        public double MeasB73VoltV { get; set; }
        public double MeasB74VoltV { get; set; }
        public double MeasB75VoltV { get; set; }
        public double MeasB76VoltV { get; set; }
        public double MeasB77VoltV { get; set; }
        public double MeasB78VoltV { get; set; }
        public double MeasB79VoltV { get; set; }
        public double MeasB80VoltV { get; set; }
        public double MeasB81VoltV { get; set; }
        public double MeasB82VoltV { get; set; }
        public double MeasB83VoltV { get; set; }
        public double MeasB84VoltV { get; set; }
        public double MeasB85VoltV { get; set; }
        public double MeasB86VoltV { get; set; }
        public double MeasB87VoltV { get; set; }
        public double MeasB88VoltV { get; set; }
        public double MeasB89VoltV { get; set; }
        public double MeasB90VoltV { get; set; }
        public double MeasB91VoltV { get; set; }
        public double MeasB92VoltV { get; set; }
        public double MeasB93VoltV { get; set; }
        public double MeasB94VoltV { get; set; }
        public double MeasB95VoltV { get; set; }
        public double MeasB96VoltV { get; set; }
        public double MeasB97VoltV { get; set; }
        public double MeasB98VoltV { get; set; }
        public double MeasB99VoltV { get; set; }
        public double MeasB100VoltV { get; set; }
        public double MeasB101VoltV { get; set; }
        public double MeasB102VoltV { get; set; }
        public double MeasB103VoltV { get; set; }
        public double MeasB104VoltV { get; set; }
        public double MeasB105VoltV { get; set; }
        public double MeasB106VoltV { get; set; }
        public double MeasB107VoltV { get; set; }
        public double MeasB108VoltV { get; set; }
        public double MeasB109VoltV { get; set; }
        public double MeasB110VoltV { get; set; }
        public double MeasB111VoltV { get; set; }
        public double MeasB112VoltV { get; set; }
        public double MeasB113VoltV { get; set; }
        public double MeasB114VoltV { get; set; }
        public double MeasB115VoltV { get; set; }
        public double MeasB116VoltV { get; set; }
        public double MeasB117VoltV { get; set; }
        public double MeasB118VoltV { get; set; }
        public double StateLoad { get; set; }

    }
}